version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: skystrike-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:18
    container_name: skystrike-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"